import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Footer from '@/components/footer'


const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Beyond Sustainability',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<html lang="en" className='bg-bc w-5/6 py-5 md:max-w-5xl mx-auto'>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={montserrat.className}>
        <Navbar />
        {children}
        
        <Footer />
        </body>

    </html>
  )
}
